# Data Understanding and Cleaning

Preface: 
- My preference is to take iterative steps and I often end up with variables that have long names, so I can back-track.  
- Also I believe I over-wrote my pickle of the results for my "Start Page" dataframe. So "start_page.pkl" actually contains some of my cleaned data edits--but for most of them I created new columns. I started with 6 columns x 1000 rows, but this pickled dataframe contains 19 columns x 881 rows, for reasons described below.

# "Start Page" Cleaning

In [9]:
import pandas as pd
unpickled_start_page_df = pd.read_pickle("./start_page.pkl")
unpickled_start_page_df

,URLs,Categories,Prices,Ratings,Durations,Titles,Ratings_spliced,Durations_spliced,Prices_spliced_from,Prices_spliced_person,Durations_spliced_str,Durations_spliced_int,Prices_spliced_str,Prices_spliced_int,Title_word_length,Ratings_int,filled_na_Ratings_median,Title_character_count,Average_word_length
0,https://www.airbnb.com/experiences/223773?loca...,WORKSHOP,From $85/person,4.99\n203 reviews\n(203),From $85/person · 5 hours,Thai Traditional Yantra Tattoo.,4.99,5 hours,$85/person,$85,5,5.0,85,85,4,4.99,4.99,27,6.750000
1,https://www.airbnb.com/experiences/358969?loca...,CRAFT CLASS,From $85/person,NaN,From $85/person · 2 hours,Try your hand at the Potters Wheel,NaN,2 hours,$85/person,$85,2,2.0,85,85,7,NaN,5.00,28,4.000000
2,https://www.airbnb.com/experiences/1140666?loc...,CRAFT CLASS,From $28/person,5.0\n2 reviews\n(2),From $28/person · 2 hours,'Wooden ring' Making Class with Nice VIew,5.0,2 hours,$28/person,$28,2,2.0,28,28,7,5.00,5.00,35,5.000000
3,https://www.airbnb.com/experiences/522186?loca...,CRAFT CLASS,From $62/person,NaN,From $62/person · 9 hours,Build your own craft and furniture.,NaN,9 hours,$62/person,$62,9,9.0,62,62,6,NaN,5.00,29,4.833333
4,https://www.airbnb.com/experiences/1005288?loc...,ART CLASS,From $160/person,NaN,From $160/person · 6 hours,Artistic Flow for your Inner Creative,NaN,6 hours,$160/person,$160,6,6.0,160,160,6,NaN,5.00,32,5.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,https://www.airbnb.com/experiences/809698?loca...,CRAFT CLASS,From $9/person,5.0\n9 reviews\n(9),From $9/person · 1.5 hours,Learn How to Make Paper Flowers,5.0,1.5 hours,$9/person,$9,1.5,1.5,9,9,6,5.00,5.00,26,4.333333
993,https://www.airbnb.com/experiences/1212487?loc...,PHOTO WALK,From $53/person,NaN,From $53/person · 2 hours,Private photoshoot in Wrocław,NaN,2 hours,$53/person,$53,2,2.0,53,53,4,NaN,5.00,26,6.500000
994,https://www.airbnb.com/experiences/987937?loca...,BOAT RIDE,From $80/person,5.0\n18 reviews\n(18),From $80/person · 6.5 hours,Découverte de la Camargue à la voile,5.0,6.5 hours,$80/person,$80,6.5,6.5,80,80,7,5.00,5.00,30,4.285714
995,https://www.airbnb.com/experiences/278438?loca...,PERSONAL STYLING,From $104/person,4.94\n34 reviews\n(34),From $104/person · 4 hours,Get your K-style Hair Perm.,4.94,4 hours,$104/person,$104,4,4.0,104,104,5,4.94,4.94,22,4.400000
998,https://www.airbnb.com/experiences/93984?locat...,ART CLASS,From $58/person,4.92\n271 reviews\n(271),From $58/person · 2 hours,Glassblowing in an artist studio,4.92,2 hours,$58/person,$58,2,2.0,58,58,5,4.92,4.92,28,5.600000

In [13]:
unpickled_start_page_df.info()
"""NOTE: I started with the first 6 columns and 1000 rows. Unfortunately, I over-wrote my original pkl after cleaning, but the original columns are otherwise intact and the code to get to the dataframe below is all listed in the steps below."""
#My loops contained a lot of string outputs--which will need to be converted to numbers for my regression modeling. 
#Some returned null values--which I verified by clicking into the corresponding pages.

<class 'pandas.core.frame.DataFrame'>
Int64Index: 881 entries, 0 to 998
Data columns (total 19 columns):
URLs                        881 non-null object
Categories                  881 non-null object
Prices                      881 non-null object
Ratings                     558 non-null object
Durations                   881 non-null object
Titles                      881 non-null object
Ratings_spliced             558 non-null object
Durations_spliced           881 non-null object
Prices_spliced_from         881 non-null object
Prices_spliced_person       881 non-null object
Durations_spliced_str       881 non-null object
Durations_spliced_int       881 non-null float64
Prices_spliced_str          881 non-null object
Prices_spliced_int          881 non-null int64
Title_word_length           881 non-null int64
Ratings_int                 558 non-null float64
filled_na_Ratings_median    881 non-null float64
Title_character_count       881 non-null int64
Average_word_length         880 non-null float64
dtypes: float64(4), int64(3), object(12)
memory usage: 137.7+ KB

'NOTE: I started with the first 6 columns and 1000 rows. Unfortunately, I over-wrote my original pkl after cleaning, but the original columns are otherwise intact and the code to get to the dataframe below is all listed in the steps below.'

Cleaning strings to include only numbers

In [15]:
unpickled_start_page_df['Durations_spliced_str'] = unpickled_start_page_df['Durations_spliced'].apply(lambda x: x.split(' hour')[0])
unpickled_start_page_df['Durations_spliced_int'] = unpickled_start_page_df['Durations_spliced_str'].astype(float)
unpickled_start_page_df['Prices_spliced_str'] = unpickled_start_page_df['Prices_spliced_person'].apply(lambda x: x.split('$')[1])
unpickled_start_page_df['Prices_spliced_str'] = unpickled_start_page_df['Prices_spliced_str'].str.replace(',', '')
unpickled_start_page_df['Prices_spliced_int'] = unpickled_start_page_df['Prices_spliced_str'].astype(int)

unpickled_start_page_df['Ratings_int'] = unpickled_start_page_df['Ratings_spliced'].astype(float)
unpickled_start_page_df

,URLs,Categories,Prices,Ratings,Durations,Titles,Ratings_spliced,Durations_spliced,Prices_spliced_from,Prices_spliced_person,Durations_spliced_str,Durations_spliced_int,Prices_spliced_str,Prices_spliced_int,Title_word_length,Ratings_int,filled_na_Ratings_median,Title_character_count,Average_word_length
0,https://www.airbnb.com/experiences/223773?loca...,WORKSHOP,From $85/person,4.99\n203 reviews\n(203),From $85/person · 5 hours,Thai Traditional Yantra Tattoo.,4.99,5 hours,$85/person,$85,5,5.0,85,85,4,4.99,4.99,27,6.750000
1,https://www.airbnb.com/experiences/358969?loca...,CRAFT CLASS,From $85/person,NaN,From $85/person · 2 hours,Try your hand at the Potters Wheel,NaN,2 hours,$85/person,$85,2,2.0,85,85,7,NaN,5.00,28,4.000000
2,https://www.airbnb.com/experiences/1140666?loc...,CRAFT CLASS,From $28/person,5.0\n2 reviews\n(2),From $28/person · 2 hours,'Wooden ring' Making Class with Nice VIew,5.0,2 hours,$28/person,$28,2,2.0,28,28,7,5.00,5.00,35,5.000000
3,https://www.airbnb.com/experiences/522186?loca...,CRAFT CLASS,From $62/person,NaN,From $62/person · 9 hours,Build your own craft and furniture.,NaN,9 hours,$62/person,$62,9,9.0,62,62,6,NaN,5.00,29,4.833333
4,https://www.airbnb.com/experiences/1005288?loc...,ART CLASS,From $160/person,NaN,From $160/person · 6 hours,Artistic Flow for your Inner Creative,NaN,6 hours,$160/person,$160,6,6.0,160,160,6,NaN,5.00,32,5.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,https://www.airbnb.com/experiences/809698?loca...,CRAFT CLASS,From $9/person,5.0\n9 reviews\n(9),From $9/person · 1.5 hours,Learn How to Make Paper Flowers,5.0,1.5 hours,$9/person,$9,1.5,1.5,9,9,6,5.00,5.00,26,4.333333
993,https://www.airbnb.com/experiences/1212487?loc...,PHOTO WALK,From $53/person,NaN,From $53/person · 2 hours,Private photoshoot in Wrocław,NaN,2 hours,$53/person,$53,2,2.0,53,53,4,NaN,5.00,26,6.500000
994,https://www.airbnb.com/experiences/987937?loca...,BOAT RIDE,From $80/person,5.0\n18 reviews\n(18),From $80/person · 6.5 hours,Découverte de la Camargue à la voile,5.0,6.5 hours,$80/person,$80,6.5,6.5,80,80,7,5.00,5.00,30,4.285714
995,https://www.airbnb.com/experiences/278438?loca...,PERSONAL STYLING,From $104/person,4.94\n34 reviews\n(34),From $104/person · 4 hours,Get your K-style Hair Perm.,4.94,4 hours,$104/person,$104,4,4.0,104,104,5,4.94,4.94,22,4.400000
998,https://www.airbnb.com/experiences/93984?locat...,ART CLASS,From $58/person,4.92\n271 reviews\n(271),From $58/person · 2 hours,Glassblowing in an artist studio,4.92,2 hours,$58/person,$58,2,2.0,58,58,5,4.92,4.92,28,5.600000

Replace my strings 'n/a' with np.NaN & convert number objects to floats

In [16]:
import numpy as np
unpickled_start_page_replaced_nulls = unpickled_start_page_df.replace('n/a',np.NaN)
unpickled_start_page_replaced_nulls['Ratings_int'] = unpickled_start_page_replaced_nulls['Ratings_spliced'].astype(float)
unpickled_start_page_replaced_nulls.isna().sum()

URLs                          0
Categories                    0
Prices                        0
Ratings                     323
Durations                     0
Titles                        0
Ratings_spliced             323
Durations_spliced             0
Prices_spliced_from           0
Prices_spliced_person         0
Durations_spliced_str         0
Durations_spliced_int         0
Prices_spliced_str            0
Prices_spliced_int            0
Title_word_length             0
Ratings_int                 323
filled_na_Ratings_median      0
Title_character_count         0
Average_word_length           1
dtype: int64

Still have some nulls with the ratings (more than 2/3 of my observations!) which I decided to fill with the median.

In [18]:
unpickled_start_page_replaced_nulls['filled_na_Ratings_median'] = unpickled_start_page_replaced_nulls['Ratings_int'].fillna(unpickled_start_page_replaced_nulls['Ratings_int'].median())

In [19]:
unpickled_start_page_replaced_nulls.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 881 entries, 0 to 998
Data columns (total 19 columns):
URLs                        881 non-null object
Categories                  881 non-null object
Prices                      881 non-null object
Ratings                     558 non-null object
Durations                   881 non-null object
Titles                      881 non-null object
Ratings_spliced             558 non-null object
Durations_spliced           881 non-null object
Prices_spliced_from         881 non-null object
Prices_spliced_person       881 non-null object
Durations_spliced_str       881 non-null object
Durations_spliced_int       881 non-null float64
Prices_spliced_str          881 non-null object
Prices_spliced_int          881 non-null int64
Title_word_length           881 non-null int64
Ratings_int                 558 non-null float64
filled_na_Ratings_median    881 non-null float64
Title_character_count       881 non-null int64
Average_word_length         880 non-null float64
dtypes: float64(4), int64(3), object(12)
memory usage: 137.7+ KB

I was interested in the length of the Titles for each Experience--by length of the titles, average length of each word, and total number of characters.

In [24]:
unpickled_start_page_replaced_nulls['Title_word_length'] = unpickled_start_page_replaced_nulls['Titles'].str.split().str.len()
unpickled_start_page_replaced_nulls['Title_character_count'] = unpickled_start_page_replaced_nulls['Titles'].str.replace('.','').str.replace(' ','').str.len()
unpickled_start_page_replaced_nulls['Average_word_length'] = unpickled_start_page_replaced_nulls['Title_character_count']/unpickled_start_page_replaced_nulls['Title_word_length']
unpickled_start_page_replaced_nulls

,URLs,Categories,Prices,Ratings,Durations,Titles,Ratings_spliced,Durations_spliced,Prices_spliced_from,Prices_spliced_person,Durations_spliced_str,Durations_spliced_int,Prices_spliced_str,Prices_spliced_int,Title_word_length,Ratings_int,filled_na_Ratings_median,Title_character_count,Average_word_length
0,https://www.airbnb.com/experiences/223773?loca...,WORKSHOP,From $85/person,4.99\n203 reviews\n(203),From $85/person · 5 hours,Thai Traditional Yantra Tattoo.,4.99,5 hours,$85/person,$85,5,5.0,85,85,4,4.99,4.99,27,6.750000
1,https://www.airbnb.com/experiences/358969?loca...,CRAFT CLASS,From $85/person,NaN,From $85/person · 2 hours,Try your hand at the Potters Wheel,NaN,2 hours,$85/person,$85,2,2.0,85,85,7,NaN,5.00,28,4.000000
2,https://www.airbnb.com/experiences/1140666?loc...,CRAFT CLASS,From $28/person,5.0\n2 reviews\n(2),From $28/person · 2 hours,'Wooden ring' Making Class with Nice VIew,5.0,2 hours,$28/person,$28,2,2.0,28,28,7,5.00,5.00,35,5.000000
3,https://www.airbnb.com/experiences/522186?loca...,CRAFT CLASS,From $62/person,NaN,From $62/person · 9 hours,Build your own craft and furniture.,NaN,9 hours,$62/person,$62,9,9.0,62,62,6,NaN,5.00,29,4.833333
4,https://www.airbnb.com/experiences/1005288?loc...,ART CLASS,From $160/person,NaN,From $160/person · 6 hours,Artistic Flow for your Inner Creative,NaN,6 hours,$160/person,$160,6,6.0,160,160,6,NaN,5.00,32,5.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,https://www.airbnb.com/experiences/809698?loca...,CRAFT CLASS,From $9/person,5.0\n9 reviews\n(9),From $9/person · 1.5 hours,Learn How to Make Paper Flowers,5.0,1.5 hours,$9/person,$9,1.5,1.5,9,9,6,5.00,5.00,26,4.333333
993,https://www.airbnb.com/experiences/1212487?loc...,PHOTO WALK,From $53/person,NaN,From $53/person · 2 hours,Private photoshoot in Wrocław,NaN,2 hours,$53/person,$53,2,2.0,53,53,4,NaN,5.00,26,6.500000
994,https://www.airbnb.com/experiences/987937?loca...,BOAT RIDE,From $80/person,5.0\n18 reviews\n(18),From $80/person · 6.5 hours,Découverte de la Camargue à la voile,5.0,6.5 hours,$80/person,$80,6.5,6.5,80,80,7,5.00,5.00,30,4.285714
995,https://www.airbnb.com/experiences/278438?loca...,PERSONAL STYLING,From $104/person,4.94\n34 reviews\n(34),From $104/person · 4 hours,Get your K-style Hair Perm.,4.94,4 hours,$104/person,$104,4,4.0,104,104,5,4.94,4.94,22,4.400000
998,https://www.airbnb.com/experiences/93984?locat...,ART CLASS,From $58/person,4.92\n271 reviews\n(271),From $58/person · 2 hours,Glassblowing in an artist studio,4.92,2 hours,$58/person,$58,2,2.0,58,58,5,4.92,4.92,28,5.600000

Sadly, my original question of how these features impact Airbnb "guest" ratings was complicated by some limitations I observed in the ratings:
- Not only did > 2/3 of my observations have null ratings, but only 182 of the 558 listings had a rating below 5.0... so the ratings in my sample are mostly clustered at 5.0. This is great for the hosts, but not helpful for my model. I decided to go another route, but I did also consider possible reasons for this pattern and paths to resolve it.

In [26]:
unpickled_start_page_replaced_nulls[unpickled_start_page_replaced_nulls['Ratings_int'] < 5.0].count()

URLs                        182
Categories                  182
Prices                      182
Ratings                     182
Durations                   182
Titles                      182
Ratings_spliced             182
Durations_spliced           182
Prices_spliced_from         182
Prices_spliced_person       182
Durations_spliced_str       182
Durations_spliced_int       182
Prices_spliced_str          182
Prices_spliced_int          182
Title_word_length           182
Ratings_int                 182
filled_na_Ratings_median    182
Title_character_count       182
Average_word_length         182
dtype: int64

# "Individual Pages"

After unpickling and importing the individual pages, I dropped the duplicate rows that contain exact matches across all columns.

In [29]:
unpickled_individual_page_df = pd.read_pickle('./individual_pages.pkl')
unpickled_individual_page_df.duplicated('URLs').value_counts()

False    889
True     111
dtype: int64

In [30]:
deduplicated_unpickled_individual_page_df = unpickled_individual_page_df.drop_duplicates()
deduplicated_unpickled_individual_page_df

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages
0,https://www.airbnb.com/experiences/223773?loca...,2.0,Up to 2 people,5,1,1,1
1,https://www.airbnb.com/experiences/358969?loca...,2.0,Up to 4 people,5,1,1,1
2,https://www.airbnb.com/experiences/1140666?loc...,2.0,Up to 4 people,5,NaN,NaN,2
3,https://www.airbnb.com/experiences/522186?loca...,NaN,Up to 10 guests ages 10 and up can attend.,2,1,NaN,Languages:\nOffered in English
4,https://www.airbnb.com/experiences/1005288?loc...,3.0,Up to 6 people,5,NaN,1,1
...,...,...,...,...,...,...,...
992,https://www.airbnb.com/experiences/809698?loca...,3.0,Up to 10 people,5,NaN,1,1
993,https://www.airbnb.com/experiences/1212487?loc...,NaN,Up to 3 guests ages 2 and up can attend.,2,NaN,NaN,Languages:\nOffered in English
994,https://www.airbnb.com/experiences/987937?loca...,2.0,Up to 6 people,5,NaN,NaN,1
995,https://www.airbnb.com/experiences/278438?loca...,1.0,Up to 3 people,5,1,1,1
998,https://www.airbnb.com/experiences/93984?locat...,NaN,Up to 5 guests ages 11 and up can attend.,2,NaN,NaN,Languages:\nOffered in English

Somehow there were about 12 rows (6 listings) where there URLs matched, but some other variable differed between the two listings. Below were my steps to remove the culprits.

In [31]:
deduplicated_unpickled_individual_page_df[deduplicated_unpickled_individual_page_df.duplicated('URLs', False) == True]

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages
227,https://www.airbnb.com/experiences/1213279?loc...,NaN,Up to 8 guests ages 18 and up can attend.,2,NaN,1,Languages:\nOffered in English
234,https://www.airbnb.com/experiences/1118272?loc...,2.0,Up to 8 people,5,1,1,2
241,https://www.airbnb.com/experiences/1179460?loc...,2.0,Up to 3 people,5,1,NaN,1
268,https://www.airbnb.com/experiences/1213279?loc...,NaN,Up to 8 guests ages 18 and up can attend.,1,NaN,1,Languages:\nOffered in English
295,https://www.airbnb.com/experiences/1179460?loc...,7.0,Up to 3 people,5,1,NaN,1
304,https://www.airbnb.com/experiences/612422?loca...,5.0,Up to 5 people,5,NaN,NaN,2
306,https://www.airbnb.com/experiences/1141687?loc...,5.0,Up to 2 people,5,NaN,1,2
323,https://www.airbnb.com/experiences/347909?loca...,NaN,Up to 6 guests ages 8 and up can attend.,1,NaN,1,Languages:\nOffered in Japanese and Korean
324,https://www.airbnb.com/experiences/347909?loca...,NaN,Up to 6 guests ages 8 and up can attend.,2,NaN,1,Languages:\nOffered in Japanese and Korean
344,https://www.airbnb.com/experiences/1118272?loc...,7.0,Up to 8 people,5,1,1,2
380,https://www.airbnb.com/experiences/1141687?loc...,1.0,Up to 2 people,5,NaN,1,2
465,https://www.airbnb.com/experiences/612422?loca...,1.0,Up to 5 people,5,NaN,NaN,2

In [33]:
dup_URLs = deduplicated_unpickled_individual_page_df[deduplicated_unpickled_individual_page_df.duplicated('URLs', False) == True]
list(dup_URLs['URLs'])

['https://www.airbnb.com/experiences/1213279?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/1118272?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/1179460?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/1213279?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/1179460?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/612422?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/1141687?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/347909?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/347909?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/1118272?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/1141687?location=crafts%20classes&source=p2',
 'https://www.airbnb.com/experiences/612422?location=crafts%20classes&source=p2']

In [34]:
deduplicated_unpickled_individual_page_df['Tags'].value_counts()

#In my review of listings with number of tags > 4, none actually had this number of tags. I did, however, identify a pattern: those with "5" actually had 1, "7" had 2, "9" had 3, and "11" had 4.

1.0     252
2.0     226
3.0      99
4.0      41
5.0      38
7.0      27
9.0      11
11.0      3
Name: Tags, dtype: int64

In [35]:
deduplicated_unpickled_individual_page_df[deduplicated_unpickled_individual_page_df['Tags'] == 7.0]

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages
174,https://www.airbnb.com/experiences/1102596?loc...,7.0,Up to 8 people,5,1,NaN,1
265,https://www.airbnb.com/experiences/1049072?loc...,7.0,Up to 5 people,5,NaN,NaN,2
267,https://www.airbnb.com/experiences/154886?loca...,7.0,Up to 9 people,5,NaN,1,2
274,https://www.airbnb.com/experiences/166172?loca...,7.0,Up to 6 people,5,1,1,2
276,https://www.airbnb.com/experiences/272903?loca...,7.0,Up to 13 people,5,NaN,1,1
278,https://www.airbnb.com/experiences/795689?loca...,7.0,Up to 4 people,5,1,1,1
281,https://www.airbnb.com/experiences/314318?loca...,7.0,Up to 4 people,5,n/a,n/a,2
286,https://www.airbnb.com/experiences/425425?loca...,7.0,Up to 10 people,5,NaN,1,1
290,https://www.airbnb.com/experiences/805176?loca...,7.0,Up to 4 people,5,NaN,1,1
294,https://www.airbnb.com/experiences/991728?loca...,7.0,Up to 10 people,5,NaN,NaN,1
295,https://www.airbnb.com/experiences/1179460?loc...,7.0,Up to 3 people,5,1,NaN,1
297,https://www.airbnb.com/experiences/967424?loca...,7.0,Up to 6 people,5,1,NaN,1
299,https://www.airbnb.com/experiences/1167857?loc...,7.0,Up to 8 people,5,1,NaN,1
308,https://www.airbnb.com/experiences/951003?loca...,7.0,Up to 2 people,5,NaN,NaN,1
309,https://www.airbnb.com/experiences/255113?loca...,7.0,Up to 4 people,5,NaN,NaN,1
311,https://www.airbnb.com/experiences/744080?loca...,7.0,Up to 5 people,5,NaN,1,1
312,https://www.airbnb.com/experiences/599829?loca...,7.0,Up to 10 people,5,n/a,n/a,1
318,https://www.airbnb.com/experiences/329410?loca...,7.0,Up to 6 people,5,NaN,NaN,2
319,https://www.airbnb.com/experiences/305187?loca...,7.0,Up to 10 people,5,NaN,NaN,2
320,https://www.airbnb.com/experiences/437698?loca...,7.0,Up to 8 people,5,n/a,n/a,1
321,https://www.airbnb.com/experiences/434822?loca...,7.0,Up to 4 people,5,NaN,1,1
344,https://www.airbnb.com/experiences/1118272?loc...,7.0,Up to 8 people,5,1,1,2
354,https://www.airbnb.com/experiences/704597?loca...,7.0,Up to 8 people,5,NaN,NaN,1
355,https://www.airbnb.com/experiences/843845?loca...,7.0,Up to 6 people,5,1,1,1
361,https://www.airbnb.com/experiences/729669?loca...,7.0,Up to 3 people,5,NaN,1,1
363,https://www.airbnb.com/experiences/328770?loca...,7.0,Up to 8 people,5,1,NaN,1
367,https://www.airbnb.com/experiences/816119?loca...,7.0,Up to 4 people,5,1,1,2

In [36]:
#change tags 11 --> 4 
deduplicated_unpickled_individual_page_df.loc[:,['Tags']] = deduplicated_unpickled_individual_page_df.loc[:,['Tags']].replace(11.0, 4.0)

/Users/kristentokunaga/anaconda3/envs/metis/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [37]:
print(deduplicated_unpickled_individual_page_df['Tags'].value_counts())
deduplicated_unpickled_individual_page_df
#['Tags'].value_counts()

1.0    252
2.0    226
3.0     99
4.0     44
5.0     38
7.0     27
9.0     11
Name: Tags, dtype: int64

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages
0,https://www.airbnb.com/experiences/223773?loca...,2.0,Up to 2 people,5,1,1,1
1,https://www.airbnb.com/experiences/358969?loca...,2.0,Up to 4 people,5,1,1,1
2,https://www.airbnb.com/experiences/1140666?loc...,2.0,Up to 4 people,5,NaN,NaN,2
3,https://www.airbnb.com/experiences/522186?loca...,NaN,Up to 10 guests ages 10 and up can attend.,2,1,NaN,Languages:\nOffered in English
4,https://www.airbnb.com/experiences/1005288?loc...,3.0,Up to 6 people,5,NaN,1,1
...,...,...,...,...,...,...,...
992,https://www.airbnb.com/experiences/809698?loca...,3.0,Up to 10 people,5,NaN,1,1
993,https://www.airbnb.com/experiences/1212487?loc...,NaN,Up to 3 guests ages 2 and up can attend.,2,NaN,NaN,Languages:\nOffered in English
994,https://www.airbnb.com/experiences/987937?loca...,2.0,Up to 6 people,5,NaN,NaN,1
995,https://www.airbnb.com/experiences/278438?loca...,1.0,Up to 3 people,5,1,1,1
998,https://www.airbnb.com/experiences/93984?locat...,NaN,Up to 5 guests ages 11 and up can attend.,2,NaN,NaN,Languages:\nOffered in English

In [40]:
#change tags 9 --> 3 
deduplicated_unpickled_individual_page_df.loc[:,['Tags']] = deduplicated_unpickled_individual_page_df.loc[:,['Tags']].replace(9.0, 3.0)
#change tags 7 --> 2 
deduplicated_unpickled_individual_page_df.loc[:,['Tags']] = deduplicated_unpickled_individual_page_df.loc[:,['Tags']].replace(7.0, 2.0)
#change tags 5--> 1 
deduplicated_unpickled_individual_page_df.loc[:,['Tags']] = deduplicated_unpickled_individual_page_df.loc[:,['Tags']].replace(5.0, 1.0)

In [41]:
deduplicated_unpickled_individual_page_df[deduplicated_unpickled_individual_page_df.duplicated('URLs', False) == True]

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages
227,https://www.airbnb.com/experiences/1213279?loc...,NaN,Up to 8 guests ages 18 and up can attend.,2,NaN,1,Languages:\nOffered in English
234,https://www.airbnb.com/experiences/1118272?loc...,2.0,Up to 8 people,5,1,1,2
241,https://www.airbnb.com/experiences/1179460?loc...,2.0,Up to 3 people,5,1,NaN,1
268,https://www.airbnb.com/experiences/1213279?loc...,NaN,Up to 8 guests ages 18 and up can attend.,1,NaN,1,Languages:\nOffered in English
295,https://www.airbnb.com/experiences/1179460?loc...,2.0,Up to 3 people,5,1,NaN,1
304,https://www.airbnb.com/experiences/612422?loca...,1.0,Up to 5 people,5,NaN,NaN,2
306,https://www.airbnb.com/experiences/1141687?loc...,1.0,Up to 2 people,5,NaN,1,2
323,https://www.airbnb.com/experiences/347909?loca...,NaN,Up to 6 guests ages 8 and up can attend.,1,NaN,1,Languages:\nOffered in Japanese and Korean
324,https://www.airbnb.com/experiences/347909?loca...,NaN,Up to 6 guests ages 8 and up can attend.,2,NaN,1,Languages:\nOffered in Japanese and Korean
344,https://www.airbnb.com/experiences/1118272?loc...,2.0,Up to 8 people,5,1,1,2
380,https://www.airbnb.com/experiences/1141687?loc...,1.0,Up to 2 people,5,NaN,1,2
465,https://www.airbnb.com/experiences/612422?loca...,1.0,Up to 5 people,5,NaN,NaN,2

In [42]:
#drop exact duplicates again
cleaned_deduplicated_unpickled_individual_page_df = deduplicated_unpickled_individual_page_df.drop_duplicates()

In [43]:
cleaned_deduplicated_unpickled_individual_page_df[cleaned_deduplicated_unpickled_individual_page_df.duplicated('URLs', False) == True]

#while there is a way to "keep first" or "keep last" when dropping, I need the first of 1 listing and the second of the other listing (because the difference was # of host photos and 2 was the accurate number); to get around this, I sorted the listings.

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages
227,https://www.airbnb.com/experiences/1213279?loc...,NaN,Up to 8 guests ages 18 and up can attend.,2,NaN,1,Languages:\nOffered in English
268,https://www.airbnb.com/experiences/1213279?loc...,NaN,Up to 8 guests ages 18 and up can attend.,1,NaN,1,Languages:\nOffered in English
323,https://www.airbnb.com/experiences/347909?loca...,NaN,Up to 6 guests ages 8 and up can attend.,1,NaN,1,Languages:\nOffered in Japanese and Korean
324,https://www.airbnb.com/experiences/347909?loca...,NaN,Up to 6 guests ages 8 and up can attend.,2,NaN,1,Languages:\nOffered in Japanese and Korean

In [45]:
#sort so I can drop the second duplicate
sorted_cleaned_deduplicated_unpickled_individual_page_df = cleaned_deduplicated_unpickled_individual_page_df.sort_values("Host_photos", ascending=False)
fully_deduplicated_unpickled_individual_page_df = sorted_cleaned_deduplicated_unpickled_individual_page_df.drop_duplicates('URLs', keep='first')
fully_deduplicated_unpickled_individual_page_df

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages
0,https://www.airbnb.com/experiences/223773?loca...,2.0,Up to 2 people,5,1,1,1
629,https://www.airbnb.com/experiences/709123?loca...,1.0,Up to 6 people,5,NaN,NaN,2
596,https://www.airbnb.com/experiences/364041?loca...,2.0,Up to 10 people,5,NaN,1,1
597,https://www.airbnb.com/experiences/947702?loca...,2.0,Up to 5 people,5,1,1,1
599,https://www.airbnb.com/experiences/264432?loca...,1.0,Up to 7 people,5,NaN,NaN,1
...,...,...,...,...,...,...,...
191,https://www.airbnb.com/experiences/686909?loca...,NaN,Up to 5 guests ages 18 and up can attend.,1,NaN,1,Languages:\nAll languages welcome
183,https://www.airbnb.com/experiences/801674?loca...,NaN,Up to 3 guests ages 16 and up can attend.,1,NaN,1,Languages:\nAll languages welcome
737,https://www.airbnb.com/experiences/971612?loca...,NaN,Up to 10 guests ages 9 and up can attend.,1,NaN,1,Languages:\nAll languages welcome
179,https://www.airbnb.com/experiences/918567?loca...,NaN,Up to 8 guests ages 16 and up can attend.,1,NaN,1,Languages:\nOffered in English
41,https://www.airbnb.com/experiences/1030435?loc...,NaN,NaN,0,n/a,n/a,NaN

Now for reformatting the columns to numerical strings.

In [51]:
#fully_deduplicated_unpickled_individual_page_df_GroupSize_strip_up_to = fully_deduplicated_unpickled_individual_page_df['GroupSize'].apply(lambda x: x.split('Up to ')[1])
fully_deduplicated_unpickled_individual_page_df_GroupSize_strip_string = fully_deduplicated_unpickled_individual_page_df['GroupSize'].str.extract('(\d+)', expand=False)
fully_deduplicated_unpickled_individual_page_df_GroupSize_strip_string

#add above column/series to dataframe
fully_deduplicated_unpickled_individual_page_df['GroupSize_strip_string'] = fully_deduplicated_unpickled_individual_page_df_GroupSize_strip_string

fully_deduplicated_unpickled_individual_page_df

dropna_GroupSize = fully_deduplicated_unpickled_individual_page_df 

#can't find any information from start page df or click back into this page: https://www.airbnb.com/experiences/1030435?location=crafts%20classes&source=p2 --so we're going to drop it
#dropna_GroupSize[dropna_GroupSize['GroupSize_strip_string'].notnull()] 
drop_blank = filledna.drop(filledna[filledna['URLs'] == 'https://www.airbnb.com/experiences/1030435?location=crafts%20classes&source=p2'].index)
drop_blank

#replace remaining nulls with zeros
filledna = dropna_GroupSize.fillna(0)
filledna[filledna['GroupSize_strip_string'] == 0]

dropna_GroupSize.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 41
Data columns (total 8 columns):
URLs                      889 non-null object
Tags                      693 non-null float64
GroupSize                 888 non-null object
Host_photos               889 non-null int64
Food                      284 non-null object
Drinks                    465 non-null object
Languages                 888 non-null object
GroupSize_strip_string    888 non-null object
dtypes: float64(1), int64(1), object(6)
memory usage: 102.5+ KB

/Users/kristentokunaga/anaconda3/envs/metis/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [54]:
#Adjusted languages string to include only numbers, where applicable
split_language = drop_blank['Languages'].str.strip('Languages:\n') 
split_language
split_language = split_language.str.strip('Offered in') 
split_language
split_language.value_counts()

1                                    514
2                                    147
English                              118
All languages welcom                  26
3                                     25
Spanish                                9
4                                      6
Germ                                   6
English and Spanish                    5
French                                 4
English and French                     4
Port                                   3
English and Port                       3
Chinese (Simplified)                   2
English and Ital                       2
German, English and French             2
German, English and Ital               2
English, Spanish and French            1
Greek and English                      1
6                                      1
English and Swedish                    1
Ko                                     1
Spanish and French                     1
English, Spanish, French and Ital      1
Japanese and Ko                        1
English, Spanish and Ital              1
Russ                                   1
Name: Languages, dtype: int64

In [55]:
#Converted remaining Languages strings to integer (number of languages) 
split_language = split_language.replace('English',1)
split_language = split_language.replace('Ko',1)
split_language = split_language.replace('Russ',1)
split_language = split_language.replace('French',1)
split_language = split_language.replace('Spanish',1)
split_language = split_language.replace('Germ',1)
split_language = split_language.replace('Port',1)
split_language = split_language.replace('Chinese (Simplified)',1)
split_language = split_language.replace('English and Spanish',2)
split_language = split_language.replace('English and French',2)
split_language = split_language.replace('English and Port',2)
split_language = split_language.replace('English and Ital',2)
split_language = split_language.replace('Spanish and French',2)
split_language = split_language.replace('Greek and English',2)
split_language = split_language.replace('Japanese and Ko',2)
split_language = split_language.replace('English and Swedish',2)
split_language = split_language.replace('German, English and Ital',3)
split_language = split_language.replace('German, English and French',3)
split_language = split_language.replace('English, Spanish and Ital',3)
split_language = split_language.replace('English, Spanish and French',3)
split_language = split_language.replace('English, Spanish, French and Ital',4)
split_language = split_language.replace('1',1)
split_language = split_language.replace('2',2)
split_language = split_language.replace('3',3)
split_language = split_language.replace('4',4)
split_language = split_language.replace('6',6)
#Setting the 26 "all languages welcome" values to 6 because median is 1 and average is close to 1, but Airbnb technically offers hosts the chance to tag up to 30 languages--which would be an extreme outlier
split_language = split_language.replace('All languages welcom',6)
split_language.value_counts()

1    658
2    165
3     31
6     27
4      7
Name: Languages, dtype: int64

In [56]:
drop_blank['Languages_cleaned'] = split_language
drop_blank.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 888 entries, 0 to 179
Data columns (total 9 columns):
URLs                      888 non-null object
Tags                      888 non-null float64
GroupSize                 888 non-null object
Host_photos               888 non-null int64
Food                      888 non-null object
Drinks                    888 non-null object
Languages                 888 non-null object
GroupSize_strip_string    888 non-null object
Languages_cleaned         888 non-null int64
dtypes: float64(1), int64(2), object(6)
memory usage: 69.4+ KB

Convert 'n/a' to np.NaN, Groupsize change string to integer

In [57]:
import numpy as np
drop_blank.replace('n/a',np.NaN, inplace=True)
drop_blank['GroupSize_strip_int'] = drop_blank['GroupSize_strip_string'].astype(int)
drop_blank.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 888 entries, 0 to 179
Data columns (total 10 columns):
URLs                      888 non-null object
Tags                      888 non-null float64
GroupSize                 888 non-null object
Host_photos               888 non-null int64
Food                      860 non-null float64
Drinks                    860 non-null float64
Languages                 888 non-null object
GroupSize_strip_string    888 non-null object
Languages_cleaned         888 non-null int64
GroupSize_strip_int       888 non-null int64
dtypes: float64(3), int64(3), object(4)
memory usage: 76.3+ KB

In [59]:
drop_blank['Food'] = drop_blank['Food'].fillna(0)
drop_blank['Drinks'] = drop_blank['Drinks'].fillna(0)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 888 entries, 0 to 179
Data columns (total 10 columns):
URLs                      888 non-null object
Tags                      888 non-null float64
GroupSize                 888 non-null object
Host_photos               888 non-null int64
Food                      888 non-null float64
Drinks                    888 non-null float64
Languages                 888 non-null object
GroupSize_strip_string    888 non-null object
Languages_cleaned         888 non-null int64
GroupSize_strip_int       888 non-null int64
dtypes: float64(3), int64(3), object(4)
memory usage: 76.3+ KB

In [ ]:
#pickle to save
final_individual_page_df = drop_blank
picked_flinal_individual_page_df = final_individual_page_df.to_pickle("./final_individual_pages.pkl")

Now it's time to merge my dataframes--but for some reason, they weren't all exact matches. So I "cleaned" them by cutting off the extranneous text after the listing number.

In [63]:
unpickled_final_start_page_df = pd.read_pickle("./start_page.pkl")
unpickled_final_individual_page_df = pd.read_pickle("./final_individual_pages.pkl")

In [64]:
cleaned_urls_start = unpickled_final_start_page_df['URLs'].apply(lambda x: x.split('?')[0])
cleaned_urls_individual = unpickled_final_individual_page_df['URLs'].apply(lambda x: x.split('?')[0])

Adding a new column to my dataframes called 'URLs_cleaned'

In [66]:
unpickled_final_start_page_df['URLs_cleaned'] = cleaned_urls_start
unpickled_final_start_page_df

unpickled_final_individual_page_df['URLs_cleaned'] = cleaned_urls_individual
unpickled_final_individual_page_df

,URLs,Tags,GroupSize,Host_photos,Food,Drinks,Languages,GroupSize_strip_string,Languages_cleaned,GroupSize_strip_int,URLs_cleaned
0,https://www.airbnb.com/experiences/223773?loca...,2.0,Up to 2 people,5,1.0,1.0,1,2,1,2,https://www.airbnb.com/experiences/223773
629,https://www.airbnb.com/experiences/709123?loca...,1.0,Up to 6 people,5,0.0,0.0,2,6,2,6,https://www.airbnb.com/experiences/709123
596,https://www.airbnb.com/experiences/364041?loca...,2.0,Up to 10 people,5,0.0,1.0,1,10,1,10,https://www.airbnb.com/experiences/364041
597,https://www.airbnb.com/experiences/947702?loca...,2.0,Up to 5 people,5,1.0,1.0,1,5,1,5,https://www.airbnb.com/experiences/947702
599,https://www.airbnb.com/experiences/264432?loca...,1.0,Up to 7 people,5,0.0,0.0,1,7,1,7,https://www.airbnb.com/experiences/264432
...,...,...,...,...,...,...,...,...,...,...,...
198,https://www.airbnb.com/experiences/1195076?loc...,0.0,Up to 10 guests ages 8 and up can attend.,1,0.0,0.0,Languages:\nOffered in English,10,1,10,https://www.airbnb.com/experiences/1195076
191,https://www.airbnb.com/experiences/686909?loca...,0.0,Up to 5 guests ages 18 and up can attend.,1,0.0,1.0,Languages:\nAll languages welcome,5,6,5,https://www.airbnb.com/experiences/686909
183,https://www.airbnb.com/experiences/801674?loca...,0.0,Up to 3 guests ages 16 and up can attend.,1,0.0,1.0,Languages:\nAll languages welcome,3,6,3,https://www.airbnb.com/experiences/801674
737,https://www.airbnb.com/experiences/971612?loca...,0.0,Up to 10 guests ages 9 and up can attend.,1,0.0,1.0,Languages:\nAll languages welcome,10,6,10,https://www.airbnb.com/experiences/971612
179,https://www.airbnb.com/experiences/918567?loca...,0.0,Up to 8 guests ages 16 and up can attend.,1,0.0,1.0,Languages:\nOffered in English,8,1,8,https://www.airbnb.com/experiences/918567

In [68]:
merged_df = unpickled_final_start_page_df.merge(unpickled_final_individual_page_df, how = 'inner', on='URLs_cleaned')

#pickle my merge too! 
merged_df = merged_df.to_pickle("./merged_df.pkl")

For my model steps, please see my next notebook: **Part3 - Data Modeling + Interpretation**